pipeline {
    agent any
	environment {
     dev_ip = "44.231.110.140"
	 master_k8s_ip = "10.173.2.193"
   }
    tools {
	nodejs "node"

    }
        stages{
            stage("Clone Project") {
                steps {
                checkout scm
                }
            }
            
	   /* stage("Test") {
                steps {
			tool name: 'localhost', type: 'org.jenkinsci.plugins.mongodb.MongoDBInstallation'
			dir ('Cashin') {
				script {
				try {
					sh 'npm install'
					sh 'npm install -g forever'
					sh 'forever list'
					sh 'forever start ./bin/www'
					sh 'forever list'
                	sh 'npm install mocha -g'
                	sh 'chmod u+x addToken.js'
                	sh ' node addToken.js'
					sh 'mocha'
					
				} catch (err){
					currentBuild.result = "UNSTABLE"
					sh 'echo $err'
				}
				}
			}
                }
            }
            */
            
            stage('Image') {
				options {
                	retry(3) 
            	}
        		steps {
        		dir ('Cashin') {
                            script {
								/* sh 'chmod u+x addToken.js'
                				sh 'node addToken.js'
								sh 'chmod u+x ApproveToken.js'
								sh 'node ApproveToken.js' */
                                docker.withServer("tcp://${dev_ip}:4243"){
								sh 'docker rm --force cashin-container  || true'
								sh 'docker rmi -f ${dev_ip}:5000/cashin || true'
                                sh 'docker build -q=true . -t ${dev_ip}:5000/cashin:${BUILD_NUMBER}'
                                sh 'docker push ${dev_ip}:5000/cashin:${BUILD_NUMBER}'
                              }
                            }
                            
	            }   
            }
            }
            
            stage('Run Image in dev ') {
                steps {
                    script {
                        docker.withServer("tcp://${dev_ip}:4243"){
        		            sh 'docker run --restart=always -d -p 3002:3002 --network=testnetwork --network-alias=cashin-container --name=cashin-container   ${dev_ip}:5000/cashin:${BUILD_NUMBER}'
                          
                        }
                    }
                }
            }
			stage ('Deploy app in K8S Cluster'){
			steps {
				dir ('Cashin') {
				sh "export dev_ip=${dev_ip}"
				sh "envsubst < PodCashin_temp.yaml > PodConfigCashin.yml"
				}
			sshagent(['k8s_ssh']){
				sh 'scp -o StrictHostKeyChecking=no Cashin/PodConfigCashin.yml admin@${master_k8s_ip}:/home/admin/'
				sh 'scp -o StrictHostKeyChecking=no Cashin/Cashin_AutoScaling.yml admin@${master_k8s_ip}:/home/admin/'			
				script {
					try{

						sh "ssh -o StrictHostKeyChecking=no admin@${master_k8s_ip} kubectl apply -f PodConfigCashin.yml" 
						sh "ssh -o StrictHostKeyChecking=no admin@${master_k8s_ip} kubectl apply -f Cashin_AutoScaling.yml"
						sh "ssh -o StrictHostKeyChecking=no admin@${master_k8s_ip} kubectl --record deployment.apps/cashin set image deployment.v1.apps/cashin cashin=${dev_ip}:5000/cashin:${BUILD_NUMBER}  || true "

					}catch(error){
						sh "ssh -o StrictHostKeyChecking=no admin@${master_k8s_ip} kubectl create -f PodConfigCashin.yml"
					}	
				}
			}
			}
			}
            
        }
}
