# apiVersion: v1
# kind: Service
# metadata:
#   name: cashin
#   namespace: default
# spec:
#   selector:
#     app: cashin
#   ports:
#   - protocol: TCP
#     port: 3002
#     targetPort: 3002
#   type: NodePort
---

kind: Service
apiVersion: v1
metadata:
  name: cashin-service
spec:
  selector:
    app: cashin
  ports:
    - port: 3002 # Default port for image

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cashin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cashin
  template:
    metadata:
      labels:
        app: cashin
    spec:
      containers:
      - name: cashin
        image: ${dev_ip}:5000/cashin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        resources:
          requests:
            # cpu 250m = 0.250 of cpu
            # memory: "64Mi"
            cpu: "250m"
         # limits:
            # memory: "128Mi"
            #cpu: "500m"
