pipeline {
    agent any
	environment {
     dev_ip = "44.231.110.140"
	 master_k8s_ip = "10.173.2.193"
   }
    tools {
	nodejs "node"

    }
        stages{
            stage("Clone Project") {
                steps {
                checkout scm
                }
            }
  /*                      
	    stage("Test") {
                steps {
			tool name: 'localhost', type: 'org.jenkinsci.plugins.mongodb.MongoDBInstallation'
			dir ('Tontine') {
				script {
				try {
					sh 'npm install'
					sh 'npm install -g forever'
					sh 'forever list'
					sh 'forever start ./bin/www'
					sh 'forever list'
                			sh 'npm install mocha -g'
					sh 'mocha --exit'
					
				} catch (err){
					currentBuild.result = "UNSTABLE"
					sh 'echo $err'
				}
				}
			}
                }
            }
*/
            stage('Image') {
				options {
                	retry(3) 
            	}
        		steps {
        		dir ('Tontine') {
                            script {
								/* sh 'chmod u+x addToken.js'
                				sh 'node addToken.js'
								sh 'chmod u+x ApproveToken.js'
								sh 'node ApproveToken.js' */
                                docker.withServer("tcp://${dev_ip}:4243"){
								sh 'docker rm --force tontine-container  || true'
								sh 'docker rmi -f ${dev_ip}:5000/tontine || true'
                                sh 'docker build --no-cache -q=true . -t ${dev_ip}:5000/tontine:${BUILD_NUMBER}'
                                sh 'docker push ${dev_ip}:5000/tontine:${BUILD_NUMBER}'
                              }
                            }
                            
	            }   
            }
            }
            
            stage('Run Image in dev ') {
                steps {
                    script {
                        docker.withServer("tcp://${dev_ip}:4243"){
        		            sh 'docker run --restart=always -d -p 3005:3005 --network=testnetwork --network-alias=tontine-container --name=tontine-container   ${dev_ip}:5000/tontine:${BUILD_NUMBER}'
                          
                        }
                    }
                }
            }
	    stage ('Deploy app in K8S Cluster'){
		steps {
			dir ('Tontine') {
				sh "export dev_ip=${dev_ip}"
				sh "envsubst < PodTontine_temp.yaml > PodConfigTontine.yml"
			}
		   sshagent(['k8s_ssh']){
			sh 'scp -o StrictHostKeyChecking=no Tontine/PodConfigTontine.yml admin@${master_k8s_ip}:/home/admin/'
			sh 'scp -o StrictHostKeyChecking=no Tontine/Tontine_AutoScaling.yml admin@${master_k8s_ip}:/home/admin/'			
			script {
				try{
					sh "ssh -o StrictHostKeyChecking=no  admin@${master_k8s_ip} kubectl apply -f PodConfigTontine.yml" 

					sh "ssh -o StrictHostKeyChecking=no  admin@${master_k8s_ip} kubectl apply -f Tontine_AutoScaling.yml"

					sh "ssh -o StrictHostKeyChecking=no  admin@${master_k8s_ip} kubectl --record deployment.apps/tontine set image deployment.v1.apps/tontine tontine=${dev_ip}:5000/tontine:${BUILD_NUMBER}  || true "

				}catch(error){
					sh "ssh -o StrictHostKeyChecking=no  admin@${master_k8s_ip} kubectl create -f PodConfigTontine.yml"
				}	
			}
		   }
		}
	    }
            
        }
}
